# Generated by Django 4.1.3 on 2022-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
