# Generated by Django 4.1.3 on 2022-12-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='photo',
        ),
    ]
